name: phpcs-check

on: push

jobs:
  initialize:
    runs-on: ubuntu-latest
    
    steps:
    - name: git_clone_repo
      uses: actions/checkout@v2
  
  check:
    runs-on: ubuntu-latest
    needs: initialize
    
    steps:
    - name: phpcs_lint-check
      run: make lint
      
